services:
  database:
    image: postgres
    restart: always
    container_name: db_container
    ports:
      - 5432:5432
    env_file:
      - ./database.env
    volumes:
      - local_pgdata:/var/lib/postgresql/data
      - ./volumes/datable:/home

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5246:80"
    env_file:
      - ./pgadmin.env
    user: "$UID:$GID"
    volumes:
      - ./volumes/pgadmin:/var/lib/pgadmin

  jupyter:
    image: jupyter:inc
    build: ./jupyter
    volumes:
      - jupyter:/home/save
    ports:
      - 8888:8888
    container_name: jupyter_notebook

volumes:
  jupyter:
  local_pgdata:
  pgadmin-data:
