services:
  database:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./database.env
    volumes:
      - local_pgdata:/var/lib/pgadmin

volumes:
  local_pgdata:
